version: '3.8'

services:
  code-executor-backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: acmw_code_executor
    ports:
      - "8000:8000"
    environment:
      - ENVIRONMENT=production
      - API_V1_STR=/api
      - CORS_ORIGINS=["http://localhost:5173", "https://herizon-code-debug.web.app", "http://localhost:3000"]
    restart: unless-stopped
